apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infrastore

commonLabels:
  app: infrastore
  managed-by: kustomize

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - pvc-media.yaml
  - pvc-db.yaml
  - secret.yaml
  - rbac.yaml          
  - network-policy.yaml 
