apiVersion: v1
kind: Service
metadata:
  name: infrastore
  namespace: infrastore
  labels:
    app: infrastore
spec:
  selector:
    app: infrastore
  ports:
    - name: http
      port: 8000
      targetPort: http
  type: ClusterIP
